const  types = { 
    SET_CURRENT_USER : "SET_CURRENT_USER", 
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
};
export default types;